Fix Ledger entry name and reference for journals
silinternational/cover-api pull request #447
Opened 2022-05-20 16:05 UTC by Baggerone

https://docs.google.com/document/d/1E4lZGAxLFJ0LnNmHVTUGoIJ_adYIVVLNblb-BV1bXyc

https://trello.com/c/VDx5noff/545-revise-journal-entry-output

2022-05-20 17:52 UTC, jason-jackson commented on application/models/claim.go
> +		le.Name = le._onlyCreateName(tx, &item, string(c.ClaimItems[i].PayoutOption), c.TotalPayout)
Should `_onlyCreateName` and `_onlyCreateReference just be a part of `NewLedgerEntry`? From what I can see, you don't need to pass anything else.

2022-05-20 17:52 UTC, jason-jackson commented on application/models/item.go
> +	le.Name = le._onlyCreateName(tx, i, "", amount)
Should `_onlyCreateName` and `_onlyCreateReference just be a part of `NewLedgerEntry`? From what I can see, you don't need to pass anything else.

2022-05-20 18:53 UTC, Schparky requested changes

2022-05-20 18:53 UTC, Schparky commented on application/migrations/20220520111000_add_reference_to_ledger_entries_table.up.fizz
> +add_column("ledger_entries", "reference", "string", {"default": ""})
Do we need a SQL update to fill in this column for existing data?

2022-05-20 18:53 UTC, Schparky commented on application/models/ledgerentry.go
> +func (le *LedgerEntry) _onlyCreateName(tx *pop.Connection, item *Item, claimPayoutType string, amount api.Currency) string {
I'm not too crazy about the leading underscore. Have you seen this done or recommended? Also, I'm not sure I understand the name. Is it named "onlyCreate" because it's only for calling on create? It seems confusing as a function name. Probably should stick with usual function naming paradigms and leave the "only create" warning to the doc comment. Try `getName` or `createNameField` or `getDescription`. Probably the latter, since it's more than just the name.

2022-05-20 18:53 UTC, Schparky commented on application/models/item.go
> +	if i == nil {
I don't have a problem with this check, but it makes me wonder what situation arose that it became necessary.

2022-05-20 18:53 UTC, Schparky commented on application/models/ledgerentry.go
> +		return "Coverage premium: Increase"
I thought it was not possible to increase coverage.

2022-05-20 18:53 UTC, Schparky commented on application/models/ledgerentry.go
> +				Description: l.Name,
If the CSV column definition is changing from "description" to "name", it probably needs to stop using the `fin.Transaction` type and use a newly created one for this new CSV definition. I was pondering how we're getting away with redefining the Sage CSV format until I realized this isn't for import into Sage.

2022-05-20 18:53 UTC, Schparky commented on application/models/policy_test.go
> +	tmplt := `%s||%s`
```suggestion
	const template = `%s||%s`
```
I kept trying to read it as "temp less than" and it just didn't make sense!

2022-05-20 18:53 UTC, Schparky commented on application/models/ledgerentry.go
> +	description = fmt.Sprintf(`%s · %s`, description, item.Policy.Name)
Is it safe to use non-ASCII characters in a CSV file? I'm particularly concerned Sage will choke on it.

2022-05-20 18:53 UTC, Schparky commented on application/models/ledgerentry.go
> +//   not including `<` and `>`.
Just a thought, curly braces are often understood as interpolation symbols, so you could get away with using them without explanation, perhaps.

2022-05-23 17:20 UTC, Baggerone commented on application/models/ledgerentry.go
> +func (le *LedgerEntry) _onlyCreateName(tx *pop.Connection, item *Item, claimPayoutType string, amount api.Currency) string {
OK. (The leading underscore is more of a Python thing for methods other developers shouldn't depend on.)

2022-05-23 17:21 UTC, Baggerone commented on application/models/ledgerentry.go
> +	description = fmt.Sprintf(`%s · %s`, description, item.Policy.Name)
What should we use there instead?

2022-05-23 17:23 UTC, Baggerone commented on application/models/ledgerentry.go
> +		return "Coverage premium: Increase"
Do we know that will always be the case?  And even for now, if that's true, won't this still work, since the `amount` will be < 0?

2022-05-23 17:36 UTC, Baggerone commented on application/models/claim.go
> +		le.Name = le._onlyCreateName(tx, &item, string(c.ClaimItems[i].PayoutOption), c.TotalPayout)
There would be other changes we would need to make to `NewLedgerEntry`. So, I think I'll leave it as I have it.

2022-05-23 17:45 UTC, Baggerone commented on application/models/ledgerentry.go
> +//   not including `<` and `>`.
Since curly braces are also understood as various other things, I think I'll leave it as is.

2022-05-23 18:09 UTC, Baggerone commented on application/models/ledgerentry.go
> +	description = fmt.Sprintf(`%s · %s`, description, item.Policy.Name)
(I've asked Alex on the Trello card.)

2022-05-23 18:37 UTC, Schparky commented on application/models/ledgerentry.go
> +		return "Coverage premium: Increase"
Yes, this code should be fine. Just checking my own understanding, as well as a question to be sure we're all on the same page.

2022-05-23 18:43 UTC, Schparky commented on application/models/ledgerentry.go
> +				Description: l.Name,
I don't know, probably not. I'm confused about this today because my comments above don't appear to be correct. This is in `ToCsv` which is used to create the CSV for Sage. In that case, we can't redefine these columns at all, I think.

2022-05-23 19:18 UTC, Schparky commented on application/models/policy.go
> +	le.Name = le._onlyCreateName(tx, nil, "", amount)
Rather than redefine the `Name` field, which would require updating previously-saved records, add new columns as necessary to save additional information needed later during report/export creation. That way the format can easily in the future, or new report definitions can be created without again mucking with historical data.

2022-05-23 19:25 UTC, Schparky commented on application/models/ledgerentry.go
> +func (le *LedgerEntry) _onlyCreateName(tx *pop.Connection, item *Item, claimPayoutType string, amount api.Currency) string {
Thinking about other ways to address this so our future selves don't have to tiptoe around these functions. Move the calling code into the LedgerEntry definition so the "client" doesn't have to worry about implementation details. We have a "NewLedgerEntry" that creates a basic template. We could do one of two things: (1) create variations on that such as "NewLedgerEntryForPolicies" and "NewLedgerEntryForClaims", or (2) leave NewLedgerEntry as it is and add additional functions that are the "second step" of Ledger Entry creation. e.g. "CreatePolicyLedgerEntry", "CreateClaimLedgerEntry". These two helper functions (currently named `_onlyCreateName` and `_onlyCreateReference`) can be non-exported. Not that that prevents misuse, since everything is still in the same package, but it uses existing Go style to "document" that these are not for external use. Better yet, move some functionality into a sub-package. I don't think that's warranted at this time, but it might be good to start thinking in that way.

2022-05-24 13:14 UTC, jason-jackson commented on application/models/claim.go
> +		le.Name = le._onlyCreateName(tx, &item, string(c.ClaimItems[i].PayoutOption), c.TotalPayout)
I'm fine with that, but amount is available from claim, which is passed to `NewLedgerEntry` as well.

2022-05-25 12:30 UTC, Baggerone commented on application/models/ledgerentry.go
> +	description = fmt.Sprintf(`%s · %s`, description, item.Policy.Name)
He said to use " / "

2022-05-25 19:29 UTC, Schparky approved these changes
Looks great. Just one suggestion.

2022-05-25 19:29 UTC, Schparky commented on application/api/ledger.go
> +	PolicyName string `json:"policy_name"`
Is a UI change waiting for this? Just wondering if we need to time the releases around this feature.

2022-05-25 19:29 UTC, Schparky commented on application/migrations/20220520111000_add_fields_to_ledger_entries_table.up.fizz
> +  WITH options AS (
Nice SQL work. I forgot about `WITH`!

2022-05-25 19:29 UTC, Schparky commented on application/models/item.go
> +	le := NewLedgerEntry(tx, i.Policy, i, nil)
I'd prefer to see `name` passed as an argument to `NewLedgerEntry` rather than `tx`. It appears that it would work in every place it's used, but I may have missed something.

2022-05-25 20:59 UTC, Baggerone commented on application/api/ledger.go
> +	PolicyName string `json:"policy_name"`
Does the UI care about an unexpected extra field?

2022-05-25 21:16 UTC, Schparky commented on application/api/ledger.go
> +	PolicyName string `json:"policy_name"`
No, but if it's expecting this field and it gets released first, that could be a problem.

2022-05-26 12:20 UTC, merged