More policy ledger table work
silinternational/cover-api pull request #449
Opened 2022-06-02 15:54 UTC by Baggerone

2022-06-02 18:39 UTC, Schparky requested changes
Some minor tweaks, and some design questions for @merchako.

2022-06-02 18:39 UTC, Schparky commented on application/models/ledgerreport.go
> +func validateMonthYearForReport(month, year int) error {
Good improvement in date validation!

2022-06-02 18:39 UTC, Schparky commented on application/models/ledgerreport.go
> +	q := "policy_id = ? AND date_entered >= ? AND date_entered <= ?"
```suggestion
	const q = "policy_id = ? AND date_entered BETWEEN ? AND ?"
```

2022-06-02 18:39 UTC, Schparky commented on application/models/policy.go
> +func (p *Policy) currentCoverage(tx *pop.Connection) api.Currency {
Maybe this could be `currentCoverageTotal` to make it more clear it's a total coverage amount.

2022-06-02 18:39 UTC, Schparky commented on application/models/claim.go
> +func (c *Claim) CreateLedgerEntry(tx *pop.Connection, statusBefore, statusAfter string) error {
`statusAfter` is always "Approved"

2022-06-02 18:39 UTC, Schparky commented on application/models/item.go
> +	tx *pop.Connection, entryType LedgerEntryType, amount api.Currency, statusBefore, statusAfter string) error {
`statusAfter` is always "Approved" if `entryType` is "New" or "Changed", and  "Inactive" if `entryType` is "Refund".

2022-06-02 18:39 UTC, Schparky commented on application/migrations/20220602112000_add_statuses_to_ledger_entries_table.up.fizz
> +add_column("ledger_entries", "status_after", "string", {"default": ""})
Since `status_after` is easily derived from `type` do we need a new database column?

2022-06-02 18:39 UTC, Schparky commented on application/migrations/20220602112000_add_statuses_to_ledger_entries_table.up.fizz
> +add_column("ledger_entries", "status_before", "string", {"default": ""})
`status_before` can mostly be derived from `type` since the state flow chart dictates what previous states are allowed. The only one that's not entirely deterministic is whether an item was auto-approved or not. @merchako what is the value in adding the "previous status" to the ledger report?

2022-06-07 20:03 UTC, Baggerone commented on application/migrations/20220602112000_add_statuses_to_ledger_entries_table.up.fizz
> +
Dropping that idea of adding the columns to the db table

2022-06-07 20:20 UTC, Baggerone commented on application/actions/policies.go
> +			Message:    fmt.Sprintf("%s, %s, must be a number", MonthParam, m),
Isn't enough that the swagger docs say they are required and an error is returned if they're invalid?

2022-06-07 20:42 UTC, Schparky commented on application/actions/policies.go
> +			Message:    fmt.Sprintf("%s, %s, must be a number", MonthParam, m),
I may have imagined that qs params should be optional. Couldn't find anything in writing to that effect.

2022-06-07 20:44 UTC, Schparky approved these changes

2022-06-08 12:17 UTC, Baggerone commented on application/actions/policies.go
> +			Message:    fmt.Sprintf("%s, %s, must be a number", MonthParam, m),
With our using the Authz middleware, I avoid using extra path parameters. And, apparently GET endpoints shouldn't expect a `body`.

2022-06-08 12:17 UTC, merged