add entityCodesCreate endpoint
silinternational/cover-api pull request #475
Opened 2023-01-24 05:16 UTC by hobbitronics

2023-01-24 05:18 UTC, hobbitronics commented on application/actions/app.go
> +	i18n "github.com/gobuffalo/mw-i18n/v2"
I don't remember changing this

2023-01-24 05:53 UTC, Schparky requested changes

2023-01-24 05:53 UTC, Schparky commented on application/actions/app.go
> +		entityCodesGroup.POST("/", entityCodesCreate)
```suggestion
		entityCodesGroup.POST("", entityCodesCreate)
```
Not sure what difference this makes, but line 198 has an empty string, so it's probably better to be consistent.

2023-01-24 05:53 UTC, Schparky commented on application/api/entitycodes.go
> +	Code string `json:"code"`
I think it would be better to create a new type `EntityCodeCreateInput` since this one is used by the update endpoint. As you have it, the update endpoint documentation will look like it's possible to change the `Code`. And future edits might actually make that possible when it must not be changed.

2023-01-24 05:53 UTC, Schparky commented on application/models/entitycode.go
> +	ec.Code = input.Code
```suggestion
	ec.ID = EntityCodeID(input.Code)
	ec.Code = input.Code
```
This is to create a V5 UUID instead of letting the ORM library, Pop, create a V4 UUID.

2023-01-24 08:58 UTC, Baggerone commented on application/actions/app.go
> +	i18n "github.com/gobuffalo/mw-i18n/v2"
Maybe your IDE changed it?

2023-01-24 08:58 UTC, Baggerone commented on application/actions/entitycodes_test.go
> +			name:       "regular user cannot create endity codes",
```suggestion
			name:       "regular user cannot create entity codes",
```

2023-01-24 08:58 UTC, Baggerone commented on application/actions/entitycodes_test.go
> +		input := api.EntityCodeInput{
No big deal, but since this doesn't change, it could go before the `for` loop.

2023-01-24 08:58 UTC, Baggerone commented on application/actions/entitycodes_test.go
> +			as.NotNil(code.Active)
In a new PR, if you're interested, it may be nice to factor out the doubled up assertions into a single function that checks both of them.

2023-01-24 22:32 UTC, hobbitronics commented on application/actions/app.go
> +	i18n "github.com/gobuffalo/mw-i18n/v2"
that's what I'm thinking

2023-01-25 00:51 UTC, Schparky commented
Looks like you accidentally committed api-docs.html. Could you remove that file, please?

2023-01-25 00:53 UTC, Schparky approved these changes

2023-01-25 00:53 UTC, Schparky commented on application/actions/app.go
> +	i18n "github.com/gobuffalo/mw-i18n/v2"
Either way, it's not a bad thing.

2023-01-25 00:53 UTC, Schparky commented on application/actions/entitycodes_test.go
> +}
```suggestion
}

```
I don't like that VSCode doesn't add a linefeed at the end of the file. Well, to be accurate, I guess it's the red symbol in Github that I don't like.

2023-01-25 01:24 UTC, merged