Feature/netsuite report zip
silinternational/cover-api pull request #518
Opened 2023-07-28 21:09 UTC by jason-jackson

NOT ready for merge as it has failing tests, input would be helpful on how to fix things.

### Changed
- Create Ledger report makes both Sage CSV and NetSuite Zip file

2023-07-28 22:29 UTC, briskt requested changes
Good solution to a complex request. I offered some suggestions for improvement.

2023-07-28 22:29 UTC, briskt commented on application/fin/fin.go
> +	ToCSV() []byte
Rather than require every format to support both csv and zip, can you just rename `BatchToCSV` to `RenderBatch`? You may need to add a second return value to provide the MIME type, but I think that seems like a better interface.

2023-07-28 22:29 UTC, briskt commented on application/fin/netsuite.go
> +	for _, transactions := range n.Transactions {
This is confusing to read. Shouldn't the struct field be `Blocks` instead of `Transactions`? Then this code would be something like:
```go
for _, block := range n.Blocks {
    for _, transactions := range block {
        ...
    }
}
```

2023-07-28 22:29 UTC, briskt commented on application/fin/netsuite.go
> +		f, err := w.Create(block + ".csv")
```suggestion
	for blockName, transactions := range n.Transactions {
		f, err := w.Create(blockName + ".csv")
```
And if my above comment is right, rename `transactions` to `block`.

2023-07-28 22:29 UTC, briskt commented on application/models/ledgerreport.go
> +		File:             *lr.File.ConvertToAPI(tx),
Rather than change the signature of `ConvertToAPI`, create a temporary variable in this function so you can take the address of the return value of `ConvertToAPI` for the new struct field. It's not a good practice to change an existing interface simply for the convenience of the caller.

For example:
```go
f := lr.Zip.ConvertToAPI(tx)
return api.LedgerReport{
    ...
    Zip: &f
    ...
```

2023-07-28 22:29 UTC, briskt commented on application/models/ledgerreport.go
> +	if lr.Zip == nil || lr.Zip.ID == uuid.Nil || reload {
It's been our practice for `LoadXxxx` functions to do only one thing. I'd like to see a separate `LoadZip` method. (Named appropriately if the name of the `Zip` field changes based on my earlier comment.)

2023-07-28 22:33 UTC, briskt commented on application/api/ledger.go
> +	Zip              *File     `json:"zip"`
One more thought. For clarity on existing database records, would it make sense to rename `File` to `SageFile` or `SageReport`? It should even be possible to rename the database column for consistency.

2023-07-29 00:08 UTC, jason-jackson commented on application/api/ledger.go
> +	Zip              *File     `json:"zip"`
Good points. This change will only be temporary, but might come up again every time provider changes.

Idea: only keep one file, but generate 2 ledger reports for each create with the same data, I think this might be possible.

Con is that there's more rows. Pro is that we don't risk losing data when removing old provider, no change to ui or database is needed.

Thoughts?

2023-07-31 04:11 UTC, jason-jackson commented on application/actions/ledger.go
> +// # LedgerReportList
Eventually would be good to update goswagger instead of continually reverting.

2023-07-31 04:40 UTC, jason-jackson commented on application/fin/netsuite.go
> +		f, err := w.Create(block + ".csv")
It's a block of transactions, so I'm fine with either way.

2023-07-31 05:14 UTC, jason-jackson commented on application/api/ledger.go
> +	Zip              *File     `json:"zip"`
I am down for changing names, UI is currently set to use `Zip`, but that is easily changeable.

2023-07-31 21:10 UTC, briskt commented on application/api/ledger.go
> +	Zip              *File     `json:"zip"`
> Personally, I think it might be better to make it so a report can have many files, not limit it to 1 or 2.

If each report generation creates multiple rows in the `ledger_reports` table, what information ties them together? Just the `created_at` column?

2023-07-31 21:23 UTC, jason-jackson commented on application/api/ledger.go
> +	Zip              *File     `json:"zip"`
I was more thinking a report would only generate a single row (unlike my other PR), just remove File from report and either make another table or add a `ledger_report_id` field to `files` table. Doing something so doing `has_many:files` works. So there would only be one report, but it would have multiple files attached.

2023-07-31 21:34 UTC, briskt approved these changes

2023-08-02 18:41 UTC, jason-jackson commented
Used alternate PR instead.

2023-08-02 18:41 UTC, closed without merging