Add fields for vehicle coverage
silinternational/cover-api pull request #532
Opened 2023-09-05 20:53 UTC by jason-jackson

### Changed

- Add year and monthly premium fields for vehicle coverage
- Change docker environment variables to be of type string instead of bool

2023-09-05 21:13 UTC, briskt requested changes

2023-09-05 21:13 UTC, briskt commented on application/models/item.go
> +	p := int(math.Round(float64(i.CoverageAmount) * domain.Env.VehiclePremiumFactor))
This function doesn't seem to be used yet, so I'm not sure if it's named incorrectly, or the wrong premium factor is used.

2023-09-05 21:13 UTC, briskt commented on application/api/items.go
> +	MonthlyPremium Currency `json:"monthly_premium"`
This isn't used anywhere. Did you intend to connect it to `CalculateMonthlyPremium`?

2023-09-05 21:13 UTC, briskt commented on application/grifts/db.go
> +    'Enabled',	8000000,	'2021-08-27 19:46:28',	'2021-08-27 19:46:28',	9, true);
```suggestion
    'Enabled',	8000000,	'2021-08-27 19:46:28',	'2021-08-27 19:46:28',	NULL, true);
```

2023-09-06 15:44 UTC, jason-jackson commented on application/models/item.go
> +	p := int(math.Round(float64(i.CoverageAmount) * domain.Env.VehiclePremiumFactor))
I've added it to ConvertToAPI now. I probably should make it nullable as I don't think we need to return monthly premiums on non-vehicles. trying to decide the best way to do that.

2023-09-06 17:19 UTC, briskt requested changes
Found the issue with your migration

2023-09-06 17:19 UTC, briskt commented on application/migrations/20230829220027_add_vehicle_coverage_fields.down.fizz
> +# drop_column("items", "year")
There's a `#` that makes this a comment, disabling the `drop_column`.
```suggestion
drop_column("items", "year")
```

2023-09-06 17:19 UTC, briskt commented on application/migrations/20230829220027_add_vehicle_coverage_fields.up.fizz
> +# add_column("items", "year", "int", {"null": true})
There's a `#` that makes this a comment, disabling the `add_column`.
```suggestion
add_column("items", "year", "int", {"null": true})
```

2023-09-06 18:44 UTC, briskt commented on application/models/item.go
> +	return i.Category.Name == "Cars and Heavy Vehicles"
Our philosophy is to never assume that child items are hydrated. So I would recommend calling `Load` on the item first.

2023-09-06 19:27 UTC, jason-jackson commented on application/models/item.go
> +	return i.Category.Name == "Cars and Heavy Vehicles"
Given I am adding premium factor as a field in the item_categories table
Then I will just remove this function until we actually need it.

2023-09-06 19:41 UTC, jason-jackson commented on application/migrations/20230906184608_add_item_category_billing_period_premium.up.fizz
> +add_column("item_categories", "billing_period", "int", {"null": true})
Would this be a better alternative?

```suggestion
add_column("item_categories", "billing_period", "int", {"default": 12})
```

2023-09-06 19:45 UTC, briskt commented on application/migrations/20230906184608_add_item_category_billing_period_premium.up.fizz
> +add_column("item_categories", "billing_period", "int", {"null": true})
Probably, yes. I prefer to avoid nullable columns when possible. I'm forgetting, though, does that work if there is already data in the table?

2023-09-06 19:48 UTC, briskt commented on application/models/itemcategory.go
> +	PremiumFactor    *float64               `db:"premium_factor"`
```suggestion
	PremiumFactor    nulls.Float64         `db:"premium_factor"`
```

2023-09-06 20:02 UTC, jason-jackson commented on application/migrations/20230906184608_add_item_category_billing_period_premium.up.fizz
> +add_column("item_categories", "billing_period", "int", {"null": true})
Yes, default is how to do add a non-null field. See https://stackoverflow.com/questions/512451/how-can-i-add-a-column-that-doesnt-allow-nulls-in-a-postgresql-database.

2023-09-06 20:20 UTC, briskt approved these changes
Looks good

2023-09-13 19:04 UTC, merged