import team vehicles
silinternational/cover-api pull request #590
Opened 2023-10-23 18:27 UTC by briskt

### Added
- Added support for importing team policies

---

### Code Checklist
- [x] Documentation (README, goswagger, etc.)
- [x] Unit tests created or updated
- [x] Run `gofmt`
- [x] Run `make swaggerspec`

2023-10-23 21:17 UTC, jason-jackson requested changes
Looks mostly good. Only `n` comment is holding me back from approving it.

2023-10-23 21:17 UTC, jason-jackson commented on application/models/policy.go
> +				return 0, 0, err
```suggestion
				return 0, 0, appErrorFromDB(err, api.ErrorQueryFailure)
```

2023-10-23 21:17 UTC, jason-jackson commented on application/models/policy.go
>  	return policiesCreated, 1, nil
I think `policiesCreated` variable isn't strictly needed, will either be `0` (error) or `1` (here).

2023-10-23 21:20 UTC, jason-jackson commented on application/models/policy.go
> +	n := 2 // first line of data is row 2 in the spreadsheet
In this case importing headers should fail on those lines, so not really a risk of bad data being entered.

2023-10-23 21:31 UTC, jason-jackson commented on application/models/policy.go
>  	for ; ; n++ {
Actually, no, would need to be set in 3rd column, I retract this comment.

2023-10-23 21:33 UTC, briskt commented on application/models/policy.go
> +	n := 2 // first line of data is row 2 in the spreadsheet
The header row is imported above this point. The variable `n` is used in three places. The first two are to print the line number in an error message. The third is to report the number of lines imported. As you observed, the third one uses `n - 2` to account for this `n := 2` assignment. I could have changed the lines that use `n` in an error message, but decided to go this route. Since it is apparently confusing this way, I will change it.

2023-10-23 21:37 UTC, briskt commented on application/models/policy.go
>  	for ; ; n++ {
Is this an improvement in readability, or just condensed?

2023-10-23 21:39 UTC, briskt commented on application/models/policy.go
> +				return 0, 0, err
Why would this be necessary? The `err` comes from `FindByTeamDetails` which passes the error through `appErrorFromDB`.

2023-10-23 21:40 UTC, briskt commented on application/models/policy.go
>  	return policiesCreated, 1, nil
Good call

2023-10-23 21:42 UTC, briskt commented on application/models/policy.go
> +				return 0, 0, err
Oops, I had commits I hadn't pushed yet.

2023-10-24 16:41 UTC, jason-jackson approved these changes
Thanks for the changes! I do think it's clearer with n+2 for line number instead.

2023-10-24 16:41 UTC, jason-jackson commented on application/models/policy.go
> +	itemName := data[ItemName]
I halfway wonder if we want to have a `Default` func in domain, not really necessary, but I see it would get used twice in this PR.

```
func Default[T comparable](a, b T) T {
	var d T
	if a == d {
		return b
	}
	return a
}
```

2023-10-24 16:46 UTC, briskt commented on application/models/policy.go
> +	itemName := data[ItemName]
Interesting idea. It's kind of like a `min` or `max`. Wonder if anyone has proposed it for inclusion as a builtin function.

2023-10-24 16:47 UTC, merged